Login Form Container
NUS-Fintech-Society/Atlas_3_Frontend pull request #27
Opened 2024-02-15 04:35 UTC by bransometan

# Pull Request

## Description
[Provide a brief description of the changes in this pull request.]

## Related Issues
[Reference any related issues that this pull request addresses or resolves.]

## Checklist
Please review and check the following before submitting your pull request:

- [ ] I have read the [CONTRIBUTING.md](../CONTRIBUTING.md) document.
- [ ] My code follows the code style of this project.
- [ ] I have written tests for my changes (if applicable).
- [ ] All new and existing tests passed.
- [ ] I have updated the documentation accordingly (if applicable).
- [ ] I have added comments to my code, particularly in areas that may be confusing.

## Screenshots (if applicable)
[Include any relevant screenshots or GIFs to visually demonstrate the changes.]

### Desktop
![image](https://github.com/NUS-Fintech-Society/Atlas_3_Frontend/assets/64539315/b305e39e-525e-4ad9-b798-021019e5e2fe)

### Mobile
![image](https://github.com/NUS-Fintech-Society/Atlas_3_Frontend/assets/64539315/c57425be-7826-4f91-9697-cccd5e4949e6)

## Additional Information
[Include any additional information that might be helpful for reviewers or maintainers.]
Not sure if I am doing it correctly. Do update me if changes is required. I think the height of the inner component depends on the size of the 2 components in login form.

## Reviewer Notes
[Optional: Include specific instructions or notes for reviewers, if necessary.]

2024-02-16 05:23 UTC, gnimnix commented
hi @bransometan , please request me as reviewer and merge into `epic/DEV-3-authentication` instead of `main`!

2024-02-18 12:10 UTC, gnimnix requested changes

2024-02-18 12:10 UTC, gnimnix commented on README.md
this file should not be changed

2024-02-18 12:10 UTC, gnimnix commented on src/assets/css/App.css
this file should not be changed

2024-02-18 12:10 UTC, gnimnix commented on src/assets/css/index.css
this file should not be changed

2024-02-18 12:10 UTC, gnimnix commented on src/assets/css/reset.css
this file should not be changed

2024-02-18 12:10 UTC, gnimnix commented on vite.config.ts.timestamp-1707232163595-fbad76be9c0df.mjs
what is this file for?

2024-02-18 12:13 UTC, gnimnix commented
@bransometan think you changed some files that should not be changed and committed the changes already. Suggest you create another branch, you can call it `TAS-2-login-form-containers-edited`. Then copy the files over.

2024-02-18 15:01 UTC, bransometan commented
Have edited the changes and submitted another PR

2024-03-16 04:22 UTC, closed without merging